/**
 * bundle-canon.ts — build script: bundle the agent-facing canon into the Worker.
 *
 * Reads the markdown under canon/ (articles, governance, specs, templates,
 * handoffs, plus canon/README.md), parses each file's YAML frontmatter, and
 * writes src/bundled-canon.ts exporting CANON_DOCS + CANON_BUNDLE metadata.
 *
 * Why: the `docs` tool used to proxy oddkit's HTTP MCP with knowledge_base_url
 * pinned to this repo. oddkit's retrieval-disclosure contract changed the
 * response shape (`result.hits` → `result.data`) and every query came back
 * empty. Ruling (captain, 2026-09-04): docs tools serve their own policy —
 * the worker carries its canon and answers from it; no external hop.
 *
 * Run: npm run bundle-canon   (CI fails if src/bundled-canon.ts is stale)
 *
 * Excluded on purpose: canon/encodings (session ledgers), canon/surfaces
 * (non-canonical ESE outputs), canon/derivatives, canon/specs/archive,
 * canon/articles/_archive, PENDING_UPLOADS.md.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, dirname, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const canonDir = join(rootDir, "canon");
const outputPath = join(rootDir, "src", "bundled-canon.ts");

const INCLUDE_DIRS = ["articles", "governance", "specs", "templates", "handoffs"];
const EXCLUDE_SEGMENTS = new Set(["_archive", "archive"]);

interface Doc {
  path: string;      // canon-relative, e.g. "articles/payload-construction.md"
  uri: string;       // klappy://canon/<path without .md>
  title: string;
  audience: string;
  tags: string[];
  stability: string;
  body: string;      // full markdown incl. frontmatter (what oddkit `get` returned)
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      if (EXCLUDE_SEGMENTS.has(name)) continue;
      out.push(...walk(p));
    } else if (name.endsWith(".md")) {
      out.push(p);
    }
  }
  return out;
}

function frontmatter(md: string): Record<string, string | string[]> {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  const fm: Record<string, string | string[]> = {};
  if (!m) return fm;
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (!kv) continue;
    const [, k, raw] = kv;
    const v = raw.trim();
    if (v.startsWith("[")) {
      fm[k] = v
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      fm[k] = v.replace(/^["']|["']$/g, "");
    }
  }
  return fm;
}

const files = [
  join(canonDir, "README.md"),
  ...INCLUDE_DIRS.flatMap((d) => walk(join(canonDir, d))),
].sort();

const docs: Doc[] = files.map((f) => {
  const body = readFileSync(f, "utf-8");
  const fm = frontmatter(body);
  const rel = relative(canonDir, f).split(sep).join("/");
  const uri = typeof fm.uri === "string" && fm.uri ? fm.uri : `klappy://canon/${rel.replace(/\.md$/, "")}`;
  const h1 = body.match(/^#\s+(.+)$/m)?.[1]?.trim();
  return {
    path: rel,
    uri,
    title: (typeof fm.title === "string" && fm.title) || h1 || rel,
    audience: typeof fm.audience === "string" ? fm.audience : "",
    tags: Array.isArray(fm.tags) ? fm.tags : [],
    stability: typeof fm.stability === "string" ? fm.stability : "",
    body,
  };
});

let sha = "unknown";
try {
  sha = execSync("git rev-parse --short=12 HEAD", { cwd: rootDir }).toString().trim();
} catch {
  // not a git checkout (e.g. a tarball build) — keep "unknown", the bundle still works
}

const bytes = docs.reduce((n, d) => n + d.body.length, 0);
const output = `// AUTO-GENERATED by scripts/bundle-canon.ts — do not edit. Re-run: npm run bundle-canon
// Source: canon/{${INCLUDE_DIRS.join(",")}} + canon/README.md (${docs.length} docs, ${bytes} bytes)
// Canon sha: ${sha}

export interface CanonDoc {
  path: string;
  uri: string;
  title: string;
  audience: string;
  tags: string[];
  stability: string;
  body: string;
}

export const CANON_BUNDLE = { sha: ${JSON.stringify(sha)}, docs: ${docs.length}, bytes: ${bytes} } as const;

export const CANON_DOCS: CanonDoc[] = ${JSON.stringify(docs, null, 0)};
`;

writeFileSync(outputPath, output);
console.log(`✓ Bundled canon → src/bundled-canon.ts (${docs.length} docs, ${bytes} bytes, sha ${sha})`);
