/**
 * bundle-telemetry-policy.ts — build script for tier-2 bundled policy.
 *
 * Reads canon/governance/telemetry-governance.md and writes
 * src/bundled-policy.ts exporting BUNDLED_POLICY as a string constant.
 *
 * Run: npx tsx scripts/bundle-telemetry-policy.ts
 *      (or: node --experimental-strip-types scripts/bundle-telemetry-policy.ts)
 *
 * Authority: klappy://canon/specs/ptxprint-mcp-v1.3-spec §6.3
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, "..");

const policyPath = join(
  rootDir,
  "canon",
  "governance",
  "telemetry-governance.md",
);
const outputPath = join(rootDir, "src", "bundled-policy.ts");

const policyContent = readFileSync(policyPath, "utf-8");

// Sanity check: the article should contain the expected heading.
if (!policyContent.includes("# Telemetry Governance")) {
  console.error(
    "ERROR: canon/governance/telemetry-governance.md does not contain expected heading.",
  );
  console.error("       The bundled policy may be malformed. Aborting.");
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/bundle-telemetry-policy.ts
// Do not edit manually. Re-run: npm run bundle-policy
//
// Source: canon/governance/telemetry-governance.md
// Generated: ${new Date().toISOString()}

export const BUNDLED_POLICY = ${JSON.stringify(policyContent)};
`;

writeFileSync(outputPath, output);
console.log(
  `✓ Bundled telemetry policy → src/bundled-policy.ts (${policyContent.length} bytes)`,
);
