/**
 * docs.ts — the canon, served by the worker itself.
 *
 * History. Session 13 made `docs(...)` a thin proxy over oddkit's HTTP MCP with
 * `knowledge_base_url` pinned to this repo ("Shape A"). It worked until oddkit
 * shipped its retrieval-disclosure contract: search results moved from
 * `result.hits` to `result.data`, this file kept reading `.hits`, and every
 * query — including the README's own examples — came back `answer: null,
 * sources: []` with `governance_source: "knowledge_base"`, which read as
 * "no such document" rather than "the upstream changed shape" (kitchen ticket
 * 2026-09-05-ptxprint-mcp-validate-and-fix, validation row D1).
 *
 * Ruling (captain, 2026-09-04): do not re-pin or re-proxy oddkit. New docs
 * tools manage and serve their own policy. This file now searches the canon
 * bundled at build time (src/bundled-canon.ts, regenerated by
 * `npm run bundle-canon`, staleness-checked in CI). Zero network, zero
 * upstream contract to drift, one fewer secret to hold.
 *
 * The public shape (DocsResult) is unchanged so existing agents keep working;
 * `served_from` is added so a reader can tell which canon sha answered.
 *
 * Vodka boundary: this file knows how to score markdown against a query. It
 * knows nothing about PTXprint semantics — the canon does.
 */

import { CANON_DOCS, CANON_BUNDLE, type CanonDoc } from "./bundled-canon.js";

// ---------- Public types (unchanged from the oddkit-proxy era) ----------

export type DocsAudience = "headless" | "gui";
export type DocsDepth = 1 | 2 | 3;

export interface DocsSource {
  uri: string;
  title: string;
  snippet: string;
  score?: number;
}

export interface DocsResult {
  answer: string | null;
  sources: DocsSource[];
  deeper: string[];
  governance_source: "knowledge_base" | "minimal";
  served_from?: string;
  error?: string;
}

// ---------- Index (built once per isolate) ----------

const STOP = new Set(
  "a an and are as at be by for from how in is it of on or that the this to what with your you".split(" "),
);

function tokens(s: string): string[] {
  return s
    .toLowerCase()
    .replace(/[`*_#>\[\]()|]/g, " ")
    .split(/[^a-z0-9.+-]+/)
    .map((t) => t.replace(/^[.+-]+|[.+-]+$/g, ""))
    .filter((t) => t.length > 1 && !STOP.has(t));
}

interface Indexed {
  doc: CanonDoc;
  tf: Map<string, number>;
  len: number;
  titleTokens: Set<string>;
  snippetSource: string;
}

function stripFrontmatter(md: string): string {
  return md.replace(/^---\n[\s\S]*?\n---\n?/, "");
}

const INDEX: Indexed[] = CANON_DOCS.map((doc) => {
  const bodyText = stripFrontmatter(doc.body);
  const toks = tokens(`${doc.title} ${doc.tags.join(" ")} ${bodyText}`);
  const tf = new Map<string, number>();
  for (const t of toks) tf.set(t, (tf.get(t) ?? 0) + 1);
  return {
    doc,
    tf,
    len: toks.length,
    titleTokens: new Set(tokens(doc.title)),
    snippetSource: bodyText,
  };
});

const DF = new Map<string, number>();
for (const ix of INDEX) for (const t of ix.tf.keys()) DF.set(t, (DF.get(t) ?? 0) + 1);
const N = INDEX.length;
const AVG_LEN = INDEX.reduce((n, ix) => n + ix.len, 0) / Math.max(1, N);

// BM25 with a title bonus. k1/b are the textbook defaults.
function score(ix: Indexed, q: string[]): number {
  const k1 = 1.2, b = 0.75;
  let s = 0;
  for (const t of q) {
    const f = ix.tf.get(t) ?? 0;
    if (!f) continue;
    const df = DF.get(t) ?? 0;
    const idf = Math.log(1 + (N - df + 0.5) / (df + 0.5));
    s += idf * ((f * (k1 + 1)) / (f + k1 * (1 - b + (b * ix.len) / AVG_LEN)));
    if (ix.titleTokens.has(t)) s += idf * 0.75;
  }
  return s;
}

function snippet(text: string, q: string[], width = 200): string {
  // First paragraph that mentions a query term; else the first paragraph.
  const paras = text.split(/\n\s*\n/).map((p) => p.replace(/\s+/g, " ").trim()).filter(Boolean);
  const hit = paras.find((p) => q.some((t) => p.toLowerCase().includes(t))) ?? paras[0] ?? "";
  return hit.length > width ? hit.slice(0, width - 1) + "…" : hit;
}

// ---------- The tool entry point ----------

const PREFERRED_TAGS: Record<DocsAudience, Set<string>> = {
  headless: new Set(["headless", "agent-kb", "mcp", "v1.2-aligned", "v1.3-aligned"]),
  gui: new Set(["gui", "training", "manual", "derivative"]),
};

export async function fetchDocs(
  query: string,
  audience: DocsAudience = "headless",
  depth: DocsDepth = 1,
): Promise<DocsResult> {
  const servedFrom = `bundled-canon@${CANON_BUNDLE.sha} (${CANON_BUNDLE.docs} docs)`;
  const q = Array.from(new Set(tokens(query)));
  if (q.length === 0) {
    return { answer: null, sources: [], deeper: suggestDeeperQueries(query), governance_source: "knowledge_base", served_from: servedFrom };
  }

  const pref = PREFERRED_TAGS[audience] ?? PREFERRED_TAGS.headless;
  const ranked = INDEX.map((ix) => {
    const base = score(ix, q);
    const matches = ix.doc.tags.filter((t) => pref.has(t)).length;
    // Audience bias is a tiebreaker: +0.5 per matching tag, never a filter.
    return { ix, base, adjusted: base > 0 ? base + matches * 0.5 : 0 };
  })
    .filter((r) => r.base > 0)
    .sort((a, b) => b.adjusted - a.adjusted);

  if (ranked.length === 0) {
    return { answer: null, sources: [], deeper: suggestDeeperQueries(query), governance_source: "knowledge_base", served_from: servedFrom };
  }

  const toSource = (r: (typeof ranked)[number], full = false): DocsSource => ({
    uri: r.ix.doc.uri,
    title: r.ix.doc.title,
    snippet: full ? r.ix.doc.body : snippet(r.ix.snippetSource, q),
    score: Math.round(r.adjusted * 1000) / 1000,
  });

  const top = ranked[0];
  const deeper = suggestDeeperFromHits(ranked.slice(0, 5).map((r) => r.ix.doc.title));

  if (depth === 1) {
    return { answer: snippet(top.ix.snippetSource, q), sources: ranked.slice(0, 5).map((r) => toSource(r)), deeper, governance_source: "knowledge_base", served_from: servedFrom };
  }

  // depth 2: full top doc; depth 3: full top three.
  const fullCount = depth === 3 ? 3 : 1;
  const sources = ranked.slice(0, 5).map((r, i) => toSource(r, i < fullCount));
  return { answer: top.ix.doc.body, sources, deeper, governance_source: "knowledge_base", served_from: servedFrom };
}

/** Exposed for tests and for `/health`-style introspection. */
export function canonBundleInfo(): { sha: string; docs: number; bytes: number } {
  return { ...CANON_BUNDLE };
}

// ---------- Internals ----------

function suggestDeeperFromHits(titles: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const t of titles) {
    if (seen.has(t)) continue;
    seen.add(t);
    out.push(`Tell me more about: ${t}`);
    if (out.length >= 3) break;
  }
  return out;
}

function suggestDeeperQueries(query: string): string[] {
  return [`${query} (broader)`, `What canon articles are available about this topic?`];
}
